name: Dynamic README puzzle injection
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  get-lichess-puzzle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node .

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            [Automated] Update README with puzzle

            Co-authored-by: moritzmyrz <64229413+moritzmyrz@users.noreply.github.com>
          title: "[Automated] Update README with new chess puzzle"
          body: Automated PR to update the README with the latest Lichess puzzle.
          branch: automated/update-puzzle
          delete-branch: true

      - name: Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number
        run: gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
